### ISSUE TITLE
Java 10 Compatibility?

### ISSUE THREAD

**Issue by bumfo** [orfjackal/retrolambda#138]
When running retrolambda with java 10 .class files, I got

```
00:00 ERROR: Failed to run Retrolambda
java.lang.IllegalArgumentException
	at net.orfjackal.retrolambda.asm.ClassReader.<init>(ClassReader.java:185)
	at net.orfjackal.retrolambda.asm.ClassReader.<init>(ClassReader.java:168)
	at net.orfjackal.retrolambda.ClassAnalyzer.analyze(ClassAnalyzer.java:25)
	at net.orfjackal.retrolambda.Retrolambda$1.visitClass(Retrolambda.java:71)
	at net.orfjackal.retrolambda.files.ClasspathVisitor.visitFile(ClasspathVisitor.java:29)
	at net.orfjackal.retrolambda.files.ClasspathVisitor.visitFile(ClasspathVisitor.java:11)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2716)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2788)
	at net.orfjackal.retrolambda.Retrolambda.visitFiles(Retrolambda.java:107)
	at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:68)
	at net.orfjackal.retrolambda.Main.main(Main.java:28)
```

**Comment by bumfo** [comment]
It seems that Java 9 .class files are not supported as well.
