### ISSUE TITLE
RetroLambda fails when passing lambda to super()

### ISSUE THREAD

**Issue by renaudcerrato** [orfjackal/retrolambda#53]
Using gradle-retrolambda 3.0.1 on Android Studio, just started seeing this today:

```
Error:Execution failed for task ':***:compileRetrolambdaDebug'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
(...)
BUILD FAILED
```

```
Error! Failed to transform some classes
java.lang.RuntimeException: java.lang.IllegalAccessException: no such method: ***.backend.ApiService$CacheObservable.lambda$new$16(String,Class)Object/invokeSpecial
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:42)
        at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.backportLambda(BackportLambdaInvocations.java:105)
        at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.visitInvokeDynamicInsn(BackportLambdaInvocations.java:94)
        at net.orfjackal.retrolambda.asm.ClassReader.readCode(ClassReader.java:1439)
        at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:1017)
        at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
        at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
        at net.orfjackal.retrolambda.Transformers.lambda$transform$4(Transformers.java:106)
        at net.orfjackal.retrolambda.Transformers$$Lambda$2/2058534881.accept(Unknown Source)
        at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:120)
        at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:106)
        at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:46)
        at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:72)
        at net.orfjackal.retrolambda.Main.main(Main.java:26)
Caused by: java.lang.IllegalAccessException: no such method: ***.backend.ApiService$CacheObservable.lambda$new$16(String,Class)Object/invokeSpecial
        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:869)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1382)
        at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:1000)
        at net.orfjackal.retrolambda.lambdas.Types.toMethodHandle(Types.java:42)
        at net.orfjackal.retrolambda.lambdas.Types.asmToJdkType(Types.java:19)
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.callBootstrapMethod(LambdaReifier.java:106)
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:37)
        ... 13 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    ***/backend/ApiService$CacheObservable.<init>(L***/backend/ApiService;Ljava/lang/String;Ljava/lang/Class;)V @9: invokedynamic
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to '***/backend/ApiService$CacheObservable'
  Current Frame:
    bci: @9
    flags: { flagThisUninit }
    locals: { uninitializedThis, '***/backend/ApiService', 'java/lang/String', 'java/lang/Class' }
    stack: { uninitializedThis, uninitializedThis, 'java/lang/String', 'java/lang/Class' }
  Bytecode:
    0x0000000: 2a2b b500 012a 2a2c 2dba 0002 0000 01b7
    0x0000010: 0003 b1                                

        at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
        ... 19 more
:***:compileRetrolambdaDebug FAILED
```

After a few A/B testing, it seems it's failing when passing a lambda to `super()`:

```
   private class CallableObservable<T> extends AbstractOnSubscribe<T, Void> {

        private final Callable<T> callable;

        private CallableObservable(Callable<T> callable) {
            this.callable = callable;
        }

        (...)
    }

    private class CacheObservable<T> extends CallableObservable<T> {

        public CacheObservable(String id, Class<T> clazz) {
            super(()-> mCache.get(id, clazz)); // <------------- HERE
        }
    }
```

Inlining the callable fixed the issue.

**Comment by orfjackal** [comment]
Actually this has nothing to do with Retrolambda. Java just doesn't allow that code, because it tries to pass a `this` reference to the lambda bootstrap method before `this` is initialized.

Here is a minimal test case for reproducing it:

```
    @Test
    public void passing_uninitialized_this_to_lambda() throws Exception {
        this.x = "foo";

        Bar b = new Bar(); // VerifyError on this line

        assertThat(b.callable.call(), is("foo"));
    }

    public String x;

    public class Bar extends Foo<String> {
        public Bar() {
            super(() -> x);
        }
    }

    public static class Foo<T> {
        public final Callable<T> callable;

        public Foo(Callable<T> callable) {
            this.callable = callable;
        }
    }
```

Output on jdk1.8.0_20, without Retrolambda:

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/orfjackal/retrolambda/test/LambdaTest$Bar.<init>(Lnet/orfjackal/retrolambda/test/LambdaTest;)V @7: invokedynamic
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to 'net/orfjackal/retrolambda/test/LambdaTest$Bar'
  Current Frame:
    bci: @7
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'net/orfjackal/retrolambda/test/LambdaTest' }
    stack: { uninitializedThis, uninitializedThis }
  Bytecode:
    0x0000000: 2a2b b500 012a 2aba 0002 0000 b700 03b1
    0x0000010:                                        
```

So this is actually a problem with the Java compiler not creating an error already at compile time.
