### ISSUE TITLE
Exception in thread "main" java.lang.ClassFormatError: Method and in class org/test/TestLambda$ComposablePredicate has illegal modifiers: 0x1

### ISSUE THREAD

**Issue by fref** [orfjackal/retrolambda#87]
I have a small test project, compiled with Java 8, retrolambdaed with the maven plugin, run with Java 7.

It runs then fails near the end.

```java
Exception in thread "main" java.lang.ClassFormatError: Method and in class org/test/TestLambda$ComposablePredicate has illegal modifiers: 0x1
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.test.TestLambda.main(TestLambda.java:43)
```

Pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.test</groupId>
    <artifactId>retrolambda-test</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <dependencies>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>14.0-rc1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.orfjackal.retrolambda</groupId>
                <artifactId>retrolambda-maven-plugin</artifactId>
                <version>2.1.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>process-main</goal>
                            <goal>process-test</goal>
                        </goals>
                        <configuration>
                            <target>1.7</target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

Test class:
```java
package org.test;

import com.google.common.base.Function;
import com.google.common.base.Predicate;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 */
@SuppressWarnings("MagicNumber")
public class TestLambda {

    public static void main(String[] args) {

        Random random = new Random();

        List<Person> persons = new ArrayList<>(30);
        for (int i = 0; 30 > i; i++) {
            persons.add(newPerson(random));
        }

        System.out.println("-----------------------------");
        System.out.println("MAJEURS");
        printPersons(persons,
                person -> 18 <= person.age,
                person -> person.email,
                System.out::println
        );
        System.out.println("-----------------------------");
        System.out.println("MINEURS");
        printPersons(persons,
                person -> 18 > person.age,
                person -> person.firstName,
                System.out::println
        );
        System.out.println("-----------------------------");
        System.out.println("majeurs, commence avec a");
        printPersons(persons,
                ((ComposablePredicate<Person>) p -> 18 <= p.age)
                        .and(p -> p.firstName.startsWith("a")),
                person -> person,
                System.out::println
        );
        System.out.println("-----------------------------");
        System.out.println("mineurs, commence avec a (with optional)");
        printPersons(persons,
                ComposablePredicate.<Person>optional(p -> 18 <= p.age, true)
                        .and(p -> p.firstName.startsWith("a")),
                person -> person,
                System.out::println
        );


    }

    private static Person newPerson(Random random) {
        Person person = new Person(nextString(random, 10), nextString(random, 10), random.nextInt(100),
                nextString(random, 5) + "@" + nextString(random, 5) + "." + nextString(random, 3));
        return person;
    }

    private static String nextString(Random random, int length) {
        StringBuilder builder = new StringBuilder(length);
        for (int i = 0; length > i; i++) {
            builder.append((char) ('a' + random.nextInt(10)));
        }
        return builder.toString();
    }

    private static <T> void printPersons(List<Person> persons, Predicate<Person> predicate, Function<Person, T> function,
            Consumer<T> consumer) {
        for (Person person : persons) {
            if (predicate.apply(person)) { consumer.accept(function.apply(person)); }
        }
    }

    public interface ComposablePredicate<T> extends Predicate<T> {

        default ComposablePredicate<T> and(Predicate<T> toAnd) {
            return t -> apply(t) && toAnd.apply(t);
        }

        default ComposablePredicate<T> andOptional(Predicate<T> toAnd, boolean optionally) {
            return and(optionally ? toAnd : identity());
        }

        default ComposablePredicate<T> identity() {
            return t -> true;
        }

        static <T> ComposablePredicate<T> optional(ComposablePredicate<T> toAnd, boolean optionally) {
            return optionally ? toAnd : toAnd.identity();
        }


    }

    public interface Consumer<T> {

        void accept(T t);
    }

    private static class Person {

        int age;

        String email;

        String firstName;

        String name;

        public Person(String name, String firstName, int age, String email) {
            this.name = name;
            this.firstName = firstName;
            this.age = age;
            this.email = email;
        }

        @Override
        public String toString() {
            final StringBuilder sb = new StringBuilder("Person{");
            sb.append("name='").append(this.name).append('\'');
            sb.append(", firstName='").append(this.firstName).append('\'');
            sb.append(", age=").append(this.age);
            sb.append(", email='").append(this.email).append('\'');
            sb.append('}');
            return sb.toString();
        }
    }
}
```

**Comment by fref** [comment]
It's a clean, one-pass build, so I thought that default methods and static methods on interfaces wouldn't be an issue.

**Comment by orfjackal** [comment]
Backporting default methods is disabled by default. Please add `<defaultMethods>true</defaultMethods>` to retrolambda-maven-plugin's configuration.

**Comment by fref** [comment]
Is it disabled by default because it's dangerous/buggy/unsafe ?

**Comment by orfjackal** [comment]
It's disabled because it has these limitations: https://github.com/orfjackal/retrolambda#known-limitations
