### ISSUE TITLE
Getting LamdaConversionException on Travis CI

### ISSUE THREAD

**Issue by RahulRvR** [orfjackal/retrolambda#88]
```
java.lang.RuntimeException: java.lang.invoke.LambdaConversionException: Type mismatch in captured lambda parameter 0: expecting class com.xx.xx.profile.ClassName$1, found class com.xx.xx.profile.ClassName
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:42)
        at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.backportLambda(BackportLambdaInvocations.java:118)
        at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.visitInvokeDynamicInsn(BackportLambdaInvocations.java:107)
        at net.orfjackal.retrolambda.asm.ClassReader.readCode(ClassReader.java:1452)
        at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:1017)
        at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
        at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
        at net.orfjackal.retrolambda.Transformers.lambda$transform$4(Transformers.java:106)
        at net.orfjackal.retrolambda.Transformers$$Lambda$2/815033865.accept(Unknown Source)
        at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:121)
        at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:106)
        at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:46)
        at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:77)
        at net.orfjackal.retrolambda.Main.main(Main.java:26)
    Caused by: java.lang.invoke.LambdaConversionException: Type mismatch in captured lambda parameter 0: expecting class com.xx.xx.profile.ClassName$1, found class com.xx.xx.profile.ClassName
        at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:256)
        at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:636)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:658)
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.callBootstrapMethod(LambdaReifier.java:110)
        at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:37)
        ... 13 more
```

**Comment by orfjackal** [comment]
Can you give more information for reproducing it? For example the source that causes that problem and/or the .class file before and after it is processed with Retrolambda.

Also please reproduce it on the latest Retrolambda. That stack trace gives more context information in Retrolambda 2.1.0 and above.

**Comment by orfjackal** [comment]
Can't reproduce without more information. Reopen if necessary.
