### ISSUE TITLE
RetroLambda Maven plugin fails

### ISSUE THREAD

**Issue by Zardoz89** [orfjackal/retrolambda#96]
I'm trying to use RetroLambda as Maven plugin , and I get this error (tested with many version of the maven plugin, from the oldest to the actual version): 

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Prueba de RetroLambda
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.4.3/maven-surefire-plugin-2.4.3.pom
6K downloaded  (maven-surefire-plugin-2.4.3.pom)
Downloading: http://repo1.maven.org/maven2/org/apache/maven/surefire/surefire/2.4.3/surefire-2.4.3.pom
7K downloaded  (surefire-2.4.3.pom)
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.4.3/maven-surefire-plugin-2.4.3.jar
22K downloaded  (maven-surefire-plugin-2.4.3.jar)
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.2/maven-jar-plugin-2.2.pom
8K downloaded  (maven-jar-plugin-2.2.pom)
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.2/maven-jar-plugin-2.2.jar
26K downloaded  (maven-jar-plugin-2.2.jar)
[INFO] [resources:resources {execution: default-resources}]
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory B:\repos\pruebas\retrolambda\src\main\resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to B:\repos\pruebas\retrolambda\target\classes
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'net.orfjackal.retrolambda:retrolambda-maven-plugin:2.3.0:process-main': Unable to load the mojo 'net.orfjackal.retrolambda:retrolambda-maven-plugin:2.3.0:process-main' in the plugin 'net.orfjackal.retrolambda:retrolambda-maven-plugin'. A required class is missing: Lorg/apache/maven/plugin/BuildPluginManager;
org.apache.maven.plugin.BuildPluginManager
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Thu May 05 09:12:22 CEST 2016
[INFO] Final Memory: 24M/226M
[INFO] ------------------------------------------------------------------------
```

I setup a minimal test with a "Hello world" program, to discard anything related to our projects pom's., but I keep getting the same problem. I adjunct the pom.xml & source code : [retrolambda.zip](https://github.com/orfjackal/retrolambda/files/250059/retrolambda.zip)

My environment consists on : 
- Windows 7 x64 bits + Cygwin
- Oracle Java 6/7/8 installed on the system. JAVA_HOME points to JDK7, but I try to set it to JDK8 to test if this the issue. On pom.xml _java8Home_ config variable points to the JDK8. 
- Maven 2.2.1

```
mvn --version
Apache Maven 2.2.1 (r801777; 2009-08-06 21:16:01+0200)
Java version: 1.8.0_45
Java home: C:\Java\jdk8\jre
Default locale: es_ES, platform encoding: Cp1252
OS name: "windows 7" version: "6.1" arch: "amd64" Family: "dos"
```

I checked that running the retrolambda.jar works without any issue

Also, I paste here the "-e" output : 

```
mvn package -e
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Prueba de RetroLambda
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory B:\repos\pruebas\retrolambda\src\main\resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to B:\repos\pruebas\retrolambda\target\classes
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'net.orfjackal.retrolambda:retrolambda-maven-plugin:2.3.0:process-main': Unable to load the mojo 'net.orfjackal.retrolambda:retrolambda-maven-plugin:2.3.0:process-main' in the plugin 'net.orfjackal.retrolambda:retrolambda-maven-plugin'. A required class is missing: Lorg/apache/maven/plugin/BuildPluginManager;
org.apache.maven.plugin.BuildPluginManager
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'net.orfjackal.retrolambda:retrolambda-maven-plugin:2.3.0:process-main': Unable to load the mojo 'net.orfjackal.retrolambda:retrolambda-maven-plugin:2.3.0:process-main' in the plugin 'net.orfjackal.retrolambda:retrolambda-maven-plugin'. A required class is missing: Lorg/apache/maven/plugin/BuildPluginManager;
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:698)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to load the mojo 'net.orfjackal.retrolambda:retrolambda-maven-plugin:2.3.0:process-main' in the plugin 'net.orfjackal.retrolambda:retrolambda-maven-plugin'. A required class is missing: Lorg/apache/maven/plugin/BuildPluginManager;
        at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:679)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:468)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        ... 17 more
Caused by: java.lang.NoClassDefFoundError: Lorg/apache/maven/plugin/BuildPluginManager;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredField(Class.java:2068)
        at hidden.org.codehaus.plexus.util.ReflectionUtils.getFieldByNameIncludingSuperclasses(ReflectionUtils.java:47)
        at hidden.org.codehaus.plexus.util.ReflectionUtils.getFieldByNameIncludingSuperclasses(ReflectionUtils.java:55)
        at org.codehaus.plexus.component.composition.FieldComponentComposer.getFieldByName(FieldComponentComposer.java:212)
        at org.codehaus.plexus.component.composition.FieldComponentComposer.findMatchingField(FieldComponentComposer.java:171)
        at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.java:62)
        at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:68)
        at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
        at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
        at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:105)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:95)
        at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:48)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
        at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:652)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.plugin.BuildPluginManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassLoader.java:195)
        at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:255)
        at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:274)
        at org.codehaus.classworlds.RealmClassLoader.loadClass(RealmClassLoader.java:214)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 37 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Thu May 05 09:12:39 CEST 2016
[INFO] Final Memory: 24M/226M
[INFO] ------------------------------------------------------------------------

```

**Comment by Zardoz89** [comment]
Ok, I found the problem. YOU SHOULD CHANGE YOUR DOCUMENTATION ABOUT RETROLAMBDA MAVEN PLUGIN TO INDICATE THAT IS NOT COMPATIBLE WITH MAVEN 2.0 ! It shows that works on maven 2.0 -> http://orfjackal.github.io/retrolambda/retrolambda-maven-plugin/plugin-info.html
